### PR TITLE
fixed structural changes

### PR DESCRIPTION
**Pull request by nbari**
Fixed structural changes

### CODE REVIEW

**Comment by iggy** [comment]
We shouldn't merge our own PRs.

**Comment by nbari** [comment]
Hi, how could I squash and maintain at the same time in sync the repo ?

thanks in advance.

**Comment by iggy** [comment]
You submit a PR and someone else merges it... The same way all the formulas work.

**Comment by nbari** [comment]
I did a squash on origin/master, that put ahead the fork, later I tried to sync back both repositories but end doing a loop of merges, basically this is what I did with out success: 

```
git remote add upstream git@github.com:nbari/epazote-formula.git
git fetch upstream
git rebase upstream/master
git push origin master --force
```

But I got:

```
Total 0 (delta 0), reused 0 (delta 0)
remote: error: GH003: Sorry, force-pushing to master is not allowed.
To git@github.com:saltstack-formulas/epazote-formula.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:saltstack-formulas/epazote-formula.git'
```

**Comment by iggy** [comment]
I'm not talking about squashing commits. I'm talking about you opening a pull request and then merging it yourself.

**Comment by nbari** [comment]
got it thanks

**Pull request merged**
